# 
# GHA Dashboard — multi-stage Dockerfile
#
# Stage 1 (deps)    — install Node 20 + npm dependencies on ubuntu:24.04
# Stage 2 (builder) — copy source, run `next build` (produces standalone output)
# Stage 3 (runner)  — minimal ubuntu:24.04 + Node runtime only; no dev deps,
#                     no source code, no npm cache in the final layer
#
# Requires next.config.ts to have `output: 'standalone'` set.
# The standalone build writes a self-contained server.js + node_modules subset
# to .next/standalone — no full node_modules install needed at runtime.
#
# Build:
#   docker build -t gha-dashboard .
#
# Run (supply all env vars from .env.local.example):
#   docker run -p 3000:3000 \
#     -e GITHUB_TOKEN=... \
#     -e GITHUB_REPOS=... \
#     -e GOOGLE_CLIENT_ID=... \
#     -e GOOGLE_CLIENT_SECRET=... \
#     -e NEXTAUTH_SECRET=... \
#     -e NEXTAUTH_URL=https://your-domain \
#     gha-dashboard
# 

# ── Stage 1: install dependencies ────────────────────────────────────────────
FROM ubuntu:24.04 AS deps

# Install Node.js 20 LTS from NodeSource
RUN apt-get update && apt-get install -y --no-install-recommends \
      curl \
      ca-certificates \
  && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
  && apt-get install -y --no-install-recommends nodejs \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy lockfile first so Docker cache is only busted when deps change
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

# ── Stage 2: build ────────────────────────────────────────────────────────────
FROM deps AS builder

COPY . .

# Disable Next.js telemetry in CI/build environments
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

# ── Stage 3: minimal runtime image ───────────────────────────────────────────
FROM ubuntu:24.04 AS runner

# Install Node.js 20 runtime only — no npm, no build tools
RUN apt-get update && apt-get install -y --no-install-recommends \
      curl \
      ca-certificates \
  && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
  && apt-get install -y --no-install-recommends nodejs \
  && rm -rf /var/lib/apt/lists/*

# Run as a non-root user (security best practice)
RUN groupadd --gid 1001 nodejs \
  && useradd --uid 1001 --gid nodejs --shell /bin/bash --create-home nextjs

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Copy the standalone server (tiny — only what Next needs to run the app)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# Static files are served by the standalone server but must be copied separately
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Public assets (favicon, robots.txt, etc.)
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# server.js is generated by `next build` when output: 'standalone' is set
CMD ["node", "server.js"]
